#!/bin/bash

docker stop consulserver
docker rm consulserver
docker run -d -p 127.0.0.1:8400:8400 -p 127.0.0.1:8500:8500 -p 127.0.0.1:8600:53/udp -p 172.17.42.1:8400:8400 -p 172.17.42.1:8500:8500 -p 172.17.42.1:8600:53/udp --name consulserver -h consulserver trusty/consul /usr/local/sbin/consul agent -server -client=0.0.0.0 -bootstrap-expect 1 -data-dir /tmp/consul
docker ps -a
